-- AlterTable
ALTER TABLE `Student` ADD COLUMN `role` ENUM('STUDENT', 'FACULTY') NOT NULL DEFAULT 'STUDENT';

-- AlterTable
ALTER TABLE `faculty` ADD COLUMN `role` ENUM('STUDENT', 'FACULTY') NOT NULL DEFAULT 'FACULTY';
